### PR TITLE
Issue 41

### LINKED ISSUE #41: Add Program Section in readme.md
## Are you a part of LGM SOC' 21 ❔
- [x] Yes ✅
- [ ] No  ❎

Add program section to represent that this project is a part of LGM-SOC'21.

### PR DESCRIPTION
**Pull request by Diksha02**
Fixes #41 🔐

## Are you a part of LGM SOC' 21 ❓
- [x] Yes ✔️
- [ ] No ✖️
## Describe the changes you've made 🏆
I have added a program section to README.md which describes that this project is a part of LGM-SOC'21.

## Type of change 🖇️
Changes in README.md

### CODE REVIEW

**Comment by Diksha02** [comment]
Please let me know if anything else was required

**Comment by kanak22** [comment]
Hey @Diksha02, for the levels and points part there is a separate issue opened by someone else so can u just remove that section from the readme :) as the other participant will add that

**Comment by Diksha02** [comment]
Sure!

**Comment by kanak22** [comment]
;)

**Pull request merged**
