### PR TITLE
Created Issues template and pull request template.

### LINKED ISSUE #9: To add ISSUE_TEMPLATES
We need to add 3 issue templates in this project to make it easy for the users to raise more issues with relevant descriptions and labels.

Issue templates to be added
- Bug Report
- Feature Request
- Design Implementation Request

### LINKED ISSUE #11: To add PULL_REQUEST_TEMPLATES
Need to add a pull request template as well. This will save the time of the contributors, as well as the project maintainers'. 

There will be a short description asking questions related to the code changes done and some checklists as well :)

Refer to this link to get a proper idea - https://github.com/stevemao/github-issue-templates

### PR DESCRIPTION
**Pull request by akshatvirmani**
fixes #9 
fixes #11

### CODE REVIEW

**Review by yashsehgal — APPROVED** [review]
Good work @akshatvirmani 👍🏽 
Everything looks good to me 💯

**Comment by yashsehgal** [comment]
@akshatvirmani There are some minor conflicts, that I want you to resolve to get an idea. 
The old code of this project is conflicting with your code changes. Please look into it :)

**Comment by akshatvirmani** [comment]
Okay

**Review by yashsehgal — APPROVED** [review]
Now everything is done perfectly. I am merging your PR

**Review by yashsehgal — COMMENTED** [review]
I am opening this PR again! for LGMSoC

**Comment by yashsehgal** [comment]
There's a small thing, Those who have created PRs, for the last time create a new branch with your name and then raise a Pull Request.

**Pull request merged**
